/**
 * PROTOTYPE ONLY — delete when the real read path lands.
 *
 * Row shapes for the design prototype, mirroring the column lists in
 * docs/DATABASE.md §4 so the screens are laid out against real fields rather
 * than invented ones. These are NOT the generated Supabase types; when the
 * Server Component reads land, `src/lib/supabase/types.ts` (generated by
 * `npm run db:types`) replaces this file entirely.
 *
 * Deliberate simplifications, all safe because nothing here talks to Postgres:
 *  - `numeric` columns are `number`, not the string Postgres returns over the
 *    wire. The real generated types will say `number` too (supabase-js parses
 *    them), so call sites don't change.
 *  - `date` / `timestamptz` are ISO strings.
 *  - Rows carry their joined display fields (e.g. `product_name` on a quote)
 *    the way a Server Component's select-with-embed would return them.
 */

// docs/DATABASE.md §5 — create type user_role as enum ('rep', 'admin')
export type UserRole = "rep" | "admin";

// create type quote_status as enum ('draft', 'pending_approval', 'approved', 'sent')
export type QuoteStatus = "draft" | "pending_approval" | "approved" | "sent";

// create type environment_type as enum ('any', 'indoor', 'outdoor')
export type EnvironmentType = "any" | "indoor" | "outdoor";

// create type quote_environment as enum ('indoor', 'outdoor')
export type QuoteEnvironment = "indoor" | "outdoor";

/**
 * PRD-009's three price-freshness states, derived from a cost's `quoted_date`
 * against `settings.freshness_warning_months` / `freshness_requote_months`.
 *
 * Stored as a literal on every fixture row rather than computed here: this
 * prototype carries no logic, and a freshness helper would be the first thing
 * to drift from the real one. The real derivation belongs in a single shared
 * module so the badge and the dashboard's stale count agree (PRD-009).
 */
export type Freshness = "current" | "aging" | "requote";

export interface Profile {
  id: string;
  full_name: string;
  role: UserRole;
}

export interface Category {
  id: string;
  name: string;
  is_active: boolean;
  sort_order: number;
}

export interface Settings {
  labor_rate: number;
  fab_markup_percent: number;
  component_markup_percent: number;
  cushion_percent: number;
  commission_percent: number;
  margin_floor_percent: number;
  freshness_warning_months: number;
  freshness_requote_months: number;
  favicon_url: string | null;
  updated_at: string;
  updated_by_name: string;
}

export interface SettingsHistoryRow {
  id: string;
  changed_field: string;
  old_value: string | null;
  new_value: string | null;
  actor_name: string;
  changed_at: string;
}

export interface Product {
  id: string;
  name: string;
  sku: string;
  description: string | null;
  vendor: string | null;
  est_labor_hours: number;
  active: boolean;
  updated_at: string;
  /** Joined aggregate — count of rows in `fab_tiers` for this product. */
  tier_count: number;
  /** Joined aggregate — worst freshness across this product's fab tiers. */
  worst_tier_freshness: Freshness;
}

export interface FabTier {
  id: string;
  product_id: string;
  qty_tier: number;
  cost: number;
  quoted_date: string;
  vendor: string | null;
  freshness: Freshness;
}

export interface ProductDefault {
  category_id: string;
  component_id: string | null;
}

export interface LibraryComponent {
  id: string;
  category_id: string;
  name: string;
  sku: string;
  vendor: string | null;
  environment: EnvironmentType;
  cost: number;
  default_labor_hours: number;
  active: boolean;
  /** Latest `price_history.quoted_date` for this component. */
  quoted_date: string;
  freshness: Freshness;
}

export interface PriceHistoryRow {
  id: string;
  source_type: "component" | "fab_tier";
  cost: number;
  quoted_date: string;
  vendor: string | null;
  changed_by_name: string;
  created_at: string;
}

/**
 * docs/DATABASE.md §4.11. The nine pricing columns are storage for
 * server-recomputed OUTPUTS (NFR-007) — the formula that produces them is
 * PRD §2A's open placeholder, so every figure below is a fixture literal and
 * nothing in this prototype recomputes one.
 */
export interface Quote {
  id: string;
  quote_number: string;
  customer_name: string;
  product_id: string;
  product_name: string;
  fab_tier_id: string;
  qty_tier: number;
  fab_cost_snapshot: number;
  environment: QuoteEnvironment;
  status: QuoteStatus;
  owner_id: string;
  owner_name: string;
  approved_by_name: string | null;
  submitted_at: string | null;
  approved_at: string | null;
  sent_at: string | null;
  total_hard_cost: number;
  total_labor_cost: number;
  cushion_amount: number;
  commission_amount: number;
  total_cost: number;
  final_price_each: number;
  gp_dollars: number;
  gp_percent: number;
  below_margin_floor: boolean;
  updated_at: string;
  /** Count of lines on this quote whose cost basis is aging or re-quote (PRD-009). */
  stale_line_count: number;
}

export interface QuoteLine {
  id: string;
  quote_id: string;
  category_id: string | null;
  component_id: string | null;
  description: string;
  is_misc: boolean;
  hard_cost: number;
  labor_hours: number;
  labor_cost: number;
  markup_percent: number;
  environment_mismatch: boolean;
  sort_order: number;
  /** Freshness of the component cost this line snapshotted (PRD-009). */
  freshness: Freshness;
  /** True when the referenced component has been deactivated (PRD-018). */
  component_deactivated: boolean;
}

export interface QuoteStatusHistoryRow {
  id: string;
  from_status: QuoteStatus | null;
  to_status: QuoteStatus;
  actor_name: string;
  changed_at: string;
}
